name: Docker
on: [push, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: mrwong99/logging
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish tagged to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: mrwong99/logging
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
    
